#!/usr/bin/env python3
"""
一次性完成小红书笔记创建和发布
检查所有前置条件 → 生成图片 → 发布笔记
"""
import subprocess
import sys
import os
import re
import json
import hashlib
from pathlib import Path
import time
import yaml
from datetime import datetime
from difflib import SequenceMatcher

# Phase 2.1: content preparation layer
from content_prep import (
    parse_markdown_frontmatter as _cp_parse_markdown_frontmatter,
    validate_digest_publish_input as _cp_validate_digest_publish_input,
    prepare_content as _cp_prepare_content,
    compress_content_smart as _cp_compress_content_smart,
    fix_dividers as _cp_fix_dividers,
    extract_tags,
    enforce_content_limit,
)

# Phase 2.2: publish execution layer
from publish_pipeline import (
    publish_note as _pp_publish_note,
    publish_payload_digest as _pp_publish_payload_digest,
)

# Phase 2.3: note_id recovery layer
from note_recovery import (
    recover_note_id_from_mcp as _nr_recover_note_id_from_mcp,
    extract_note_id_from_url as _nr_extract_note_id_from_url,
)

# Phase 2.4: publish state management layer
from publish_state import (
    get_published_lock_path as _ps_get_published_lock_path,
    check_published_today as _ps_check_published_today,
    mark_published as _ps_mark_published,
    write_pending_sync as _ps_write_pending_sync,
    read_pending_sync as _ps_read_pending_sync,
    clear_pending_sync as _ps_clear_pending_sync,
    infer_task_id_from_images as _ps_infer_task_id_from_images,
)

# Phase 2.5: orchestration layer
from orchestrator import (
    run_publish_flow as _orch_run_publish_flow,
    run_recovery_flow as _orch_run_recovery_flow,
)

# 加载 ~/.env 环境变量
def load_env_file():
    """手动加载 .env 文件（不依赖 python-dotenv）"""
    env_path = Path.home() / ".env"
    if env_path.exists():
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    # 处理 export KEY=value 格式
                    if line.startswith('export '):
                        line = line[7:]
                    key, _, value = line.partition('=')
                    key = key.strip()
                    value = value.strip().strip('"\'')  # 去除引号
                    if key and key not in os.environ:
                        os.environ[key] = value

load_env_file()

# 路径配置
SKILL_DIR = Path(__file__).parent.parent
PUBLISH_SCRIPT = SKILL_DIR / "scripts" / "publish_xhs.py"
PENDING_SYNC_FILE = SKILL_DIR / "pending_sync.json"

# Prefer project venv Python over system default (macOS ships 3.9 which lacks PEP 604)
_MYENV_PYTHON = Path.home() / "myenv" / "bin" / "python3"
PYTHON_BIN = str(_MYENV_PYTHON) if _MYENV_PYTHON.exists() else sys.executable
# - Python scripts should NOT make "intelligent" decisions
# - Title optimization should be done by Sonnet spawning Kimi (AI-based)
# - Tags should be generated by Kimi during rewrite phase (in front matter)
#
# Correct flow:
# 1. Sonnet spawns Kimi: rewrite content → outputs front matter with title + tags
# 2. If title > 20: Sonnet spawns Kimi again: "optimize title to 15-20 chars"
# 3. Python only validates and raises error if still invalid




# === Phase 2.1: Redirected to content_prep.py ===
# Old definitions kept as comments for reference; active code delegates to content_prep.

def parse_markdown_frontmatter(md_file):
    """Redirected to content_prep.py"""
    return _cp_parse_markdown_frontmatter(md_file)


def validate_digest_publish_input(md_file, metadata, skip_cover):
    """Redirected to content_prep.py"""
    return _cp_validate_digest_publish_input(md_file, metadata, skip_cover)


def prepare_content(md_file, doc_style='tech'):
    """Redirected to content_prep.py"""
    return _cp_prepare_content(md_file, doc_style)


def compress_content_smart(content, target_length):
    """Redirected to content_prep.py"""
    return _cp_compress_content_smart(content, target_length)


def fix_dividers(text):
    """Redirected to content_prep.py"""
    return _cp_fix_dividers(text)

# === End Phase 2.1 redirects ===

# ===== MCP 并发锁 + 发布幂等 =====
import atexit
from datetime import datetime, timedelta, timezone

MCP_LOCK_FILE = Path("/tmp/xhs_mcp.lock")
PUBLISHED_LOCK_DIR = SKILL_DIR / "locks"
PUBLISHED_LOCK_DIR.mkdir(exist_ok=True)

def get_env_int(name: str, default: int, min_value: int = 0, max_value = None) -> int:
    """Read integer env with clamp and safe fallback."""
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        value = int(raw)
    except ValueError:
        print(f"  ⚠️ 环境变量 {name} 非整数({raw})，使用默认值 {default}")
        return default

    if value < min_value:
        print(f"  ⚠️ 环境变量 {name}={value} 低于最小值 {min_value}，使用 {min_value}")
        value = min_value
    if max_value is not None and value > max_value:
        print(f"  ⚠️ 环境变量 {name}={value} 高于最大值 {max_value}，使用 {max_value}")
        value = max_value
    return value


def get_env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name, "").strip().lower()
    if not raw:
        return default
    return raw in {"1", "true", "yes", "on"}


# MCP performance knobs (可通过 ~/.env 覆盖)
MCP_LOCK_MAX_WAIT = get_env_int("XHS_MCP_LOCK_MAX_WAIT", 300, min_value=0, max_value=2400)
MCP_LOCK_POLL_INTERVAL = get_env_int("XHS_MCP_LOCK_POLL_INTERVAL", 5, min_value=1, max_value=60)
MCP_STALE_LOCK_MINUTES = get_env_int("XHS_MCP_STALE_LOCK_MINUTES", 20, min_value=1, max_value=180)
MCP_CONNECT_TIMEOUT = get_env_int("XHS_MCP_CONNECT_TIMEOUT", 1, min_value=1, max_value=5)
MCP_START_WAIT_SECONDS = get_env_int("XHS_MCP_START_WAIT_SECONDS", 3, min_value=0, max_value=30)
MCP_HTTP_TIMEOUT = get_env_int("XHS_MCP_HTTP_TIMEOUT", 120, min_value=10, max_value=600)
MCP_ME_TIMEOUT = get_env_int("XHS_MCP_ME_TIMEOUT", 10, min_value=3, max_value=60)
MCP_MAX_ATTEMPTS = get_env_int("XHS_MCP_MAX_ATTEMPTS", 2, min_value=1, max_value=5)
MCP_RETRY_WAIT_SECONDS = get_env_int("XHS_MCP_RETRY_WAIT_SECONDS", 3, min_value=0, max_value=60)
MCP_NOTE_ID_RECOVERY_MAX_WAIT = get_env_int("XHS_MCP_NOTE_ID_RECOVERY_MAX_WAIT", 120, min_value=0, max_value=300)
MCP_NOTE_ID_RECOVERY_INTERVAL = get_env_int("XHS_MCP_NOTE_ID_RECOVERY_INTERVAL", 3, min_value=1, max_value=15)
MCP_NOTE_ID_RECOVERY_REQUEST_TIMEOUT = get_env_int("XHS_MCP_NOTE_ID_RECOVERY_REQUEST_TIMEOUT", 12, min_value=3, max_value=30)
MCP_LATEST_FEED_TIME_WINDOW_SECONDS = get_env_int("XHS_MCP_LATEST_FEED_TIME_WINDOW_SECONDS", 900, min_value=30, max_value=7200)
MCP_LATEST_FEED_MIN_TITLE_SIMILARITY_BPS = get_env_int("XHS_MCP_LATEST_FEED_MIN_TITLE_SIMILARITY_BPS", 65, min_value=10, max_value=100)
MCP_CONTENT_MAX_LENGTH = get_env_int("XHS_MCP_CONTENT_MAX_LENGTH", 2000, min_value=200, max_value=3000)
PUBLISH_SOFT_CONTENT_LIMIT = get_env_int("XHS_PUBLISH_SOFT_CONTENT_LIMIT", 1900, min_value=200, max_value=3000)
MCP_FALLBACK_ON_FAIL = get_env_bool("XHS_MCP_FALLBACK_ON_FAIL", default=False)


def acquire_mcp_lock(
    task_name: str,
    max_wait: int = MCP_LOCK_MAX_WAIT,
    poll_interval: int = MCP_LOCK_POLL_INTERVAL,
    stale_lock_minutes: int = MCP_STALE_LOCK_MINUTES,
) -> bool:
    waited = 0
    while waited < max_wait:
        if MCP_LOCK_FILE.exists():
            try:
                pid, name, ts = MCP_LOCK_FILE.read_text().strip().split("|")
                if datetime.now() - datetime.fromisoformat(ts) > timedelta(minutes=stale_lock_minutes):
                    print(f"  ⚠️ 僵死锁({name})，强制清除")
                    MCP_LOCK_FILE.unlink(missing_ok=True)
                else:
                    sleep_for = min(poll_interval, max_wait - waited)
                    print(f"  ⏳ MCP被{name}占用，{sleep_for}s后重试... (已等{waited}s)")
                    time.sleep(sleep_for)
                    waited += sleep_for
                    continue
            except Exception:
                MCP_LOCK_FILE.unlink(missing_ok=True)
        MCP_LOCK_FILE.write_text(f"{os.getpid()}|{task_name}|{datetime.now().isoformat()}")
        atexit.register(release_mcp_lock)
        print(f"  🔒 MCP锁已获取: {task_name}")
        return True
    if max_wait == 0 and not MCP_LOCK_FILE.exists():
        MCP_LOCK_FILE.write_text(f"{os.getpid()}|{task_name}|{datetime.now().isoformat()}")
        atexit.register(release_mcp_lock)
        print(f"  🔒 MCP锁已获取: {task_name}")
        return True
    print(f"  ❌ 等待MCP锁超时({max_wait}s)")
    return False

def release_mcp_lock():
    if MCP_LOCK_FILE.exists():
        try:
            if MCP_LOCK_FILE.read_text().strip().startswith(str(os.getpid())):
                MCP_LOCK_FILE.unlink(missing_ok=True)
                print("  🔓 MCP锁已释放")
        except Exception:
            pass

# === Phase 2.4: Redirected to publish_state.py (block 1) ===

def get_published_lock_path(date_str: str, lock_type: str = "narrative") -> Path:
    """Redirected to publish_state.py"""
    return _ps_get_published_lock_path(PUBLISHED_LOCK_DIR, date_str, lock_type)


def check_published_today(date_str: str, lock_type: str = "narrative") -> tuple:
    """Redirected to publish_state.py"""
    return _ps_check_published_today(PUBLISHED_LOCK_DIR, date_str, lock_type)


def mark_published(date_str: str, note_id: str, title: str, lock_type: str = "narrative"):
    """Redirected to publish_state.py"""
    return _ps_mark_published(PUBLISHED_LOCK_DIR, date_str, note_id, title, lock_type)

# === End Phase 2.4 redirects (block 1) ===


# === Phase 2.3: Redirected to note_recovery.py ===

def _extract_note_id_from_url(url: str) -> str:
    """Redirected to note_recovery.py"""
    return _nr_extract_note_id_from_url(url)


def recover_note_id_from_mcp(
    mcp_base: str,
    expected_title: str,
    max_wait: int = MCP_NOTE_ID_RECOVERY_MAX_WAIT,
    interval: int = MCP_NOTE_ID_RECOVERY_INTERVAL,
    request_timeout: int = MCP_NOTE_ID_RECOVERY_REQUEST_TIMEOUT,
) -> tuple[str, str, dict]:
    """Redirected to note_recovery.py — wires up default constants."""
    return _nr_recover_note_id_from_mcp(
        mcp_base,
        expected_title,
        max_wait=max_wait,
        interval=interval,
        request_timeout=request_timeout,
    )

# === End Phase 2.3 redirects ===


def check_cookie_expiry() -> tuple:
    """本地检查cookie过期，避免触发go-rod"""
    cookies_file = SKILL_DIR / "tools" / "cookies.json"
    if not cookies_file.exists():
        return False, "cookies.json不存在"
    try:
        import json
        cookies = json.loads(cookies_file.read_text())
        now = datetime.now().timestamp()
        for c in cookies:
            if c.get("expires", 0) > now + 3600:
                return True, f"cookie有效(至少剩余{((c['expires']-now)/3600):.1f}h)"
        return False, "所有cookie已过期或即将过期"
    except Exception as e:
        return True, f"cookie检查异常({e})，跳过"
# ===== END MCP 并发锁 =====

# [Phase 2.1] compress_content_smart moved to content_prep.py

# [Phase 2.1] fix_dividers moved to content_prep.py

# === Phase 2.4: Redirected to publish_state.py ===

def write_pending_sync(note_id, title, xhs_url, task_id, image_dir, tags, content, extra: dict = None):
    """Redirected to publish_state.py"""
    return _ps_write_pending_sync(PENDING_SYNC_FILE, note_id, title, xhs_url, task_id, image_dir, tags, content, extra)


def read_pending_sync():
    """Redirected to publish_state.py"""
    return _ps_read_pending_sync(PENDING_SYNC_FILE)


def clear_pending_sync():
    """Redirected to publish_state.py"""
    return _ps_clear_pending_sync(PENDING_SYNC_FILE)


def infer_task_id_from_images(images: list) -> str:
    """Redirected to publish_state.py"""
    return _ps_infer_task_id_from_images(images)

# === End Phase 2.4 redirects (block 2) ===


def check_prerequisites():
    """检查所有前置条件"""
    print("🔍 检查前置条件...\n")

    # 1. 检查 XHS_COOKIE
    env_file = SKILL_DIR / ".env"
    if not env_file.exists():
        print("❌ 缺少 .env 配置文件")
        print(f"   请在 {env_file} 中配置:")
        print("   XHS_COOKIE=你的小红书Cookie")
        return False

    # 读取 .env 检查 Cookie
    with open(env_file) as f:
        content = f.read()
        if "XHS_COOKIE=" not in content or "XHS_COOKIE=your_cookie" in content:
            print("❌ XHS_COOKIE 未正确配置")
            print(f"   请编辑 {env_file}")
            return False

    print("✓ XHS_COOKIE 已配置")

    # 2. 检查图片生成脚本
    img_script = SKILL_DIR / "scripts" / "generate_xhs_images.py"
    if not img_script.exists():
        print(f"❌ 图片生成脚本未找到: {img_script}")
        return False

    print("✓ 图片生成脚本可用")

    # 3. 检查 uv
    result = subprocess.run(["which", "uv"])
    if result.returncode != 0:
        print("❌ uv 未安装")
        print("   运行: brew install uv")
        return False

    print("✓ uv 已安装")

    # 4. 检查发布脚本依赖
    try:
        import dotenv
        import requests
        print("✓ 发布脚本依赖已安装")
    except ImportError as e:
        print(f"❌ 缺少依赖: {e}")
        print("   建议使用 pipx 安装:")
        print("   pipx install python-dotenv requests xhs")
        return False

    print()
    return True


# find_available_api_key() removed - API key rotation now handled by generate_xhs_images.py


# [Phase 2.1] parse_markdown_frontmatter moved to content_prep.py


# [Phase 2.1] validate_digest_publish_input moved to content_prep.py


def extract_generated_images(combined_output: str, skill_dir: Path, task_id: str) -> list[str]:
    """
    Extract only current task images from generator output.
    Prevent stale images from previous runs being mixed into publish payload.
    """
    cover_path = None
    image_map: dict[int, Path] = {}
    pattern = re.compile(rf"{re.escape(task_id)}_(cover|image_(\d+))\.(?:jpg|png)")

    for raw_line in combined_output.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        m = pattern.search(line)
        if not m:
            continue
        rel_name = m.group(0)
        p = skill_dir / rel_name
        if not p.exists():
            continue
        if m.group(1) == "cover":
            cover_path = p
        else:
            idx = int(m.group(2))
            image_map[idx] = p

    ordered = []
    if cover_path:
        ordered.append(str(cover_path))
    ordered.extend(str(image_map[i]) for i in sorted(image_map))

    if ordered:
        return ordered

    # Fallback only within current task_id (never scan all historical files).
    cover = skill_dir / f"{task_id}_cover.jpg"
    if not cover.exists():
        cover = skill_dir / f"{task_id}_cover.png"
    if cover.exists():
        ordered.append(str(cover))

    for p in sorted(skill_dir.glob(f"{task_id}_image_*.jpg")):
        ordered.append(str(p))
    if not ordered:
        for p in sorted(skill_dir.glob(f"{task_id}_image_*.png")):
            ordered.append(str(p))
    return ordered


# generate_images() function removed - now using standalone generate_xhs_images.py script
# All image generation logic (single/multi-image, prompts, API rotation) is in the new script


def run_command_streaming(cmd, cwd=None):
    """Run subprocess and stream combined stdout/stderr in real time."""
    proc = subprocess.Popen(
        cmd,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    lines = []
    if proc.stdout is not None:
        for line in proc.stdout:
            lines.append(line)
            sys.stdout.write(line)
            sys.stdout.flush()
    return_code = proc.wait()
    return return_code, "".join(lines)


# [Phase 2.1] prepare_content moved to content_prep.py

# === Phase 2.2: Redirected to publish_pipeline.py ===

def _publish_payload_digest(title, desc, images, topics) -> str:
    """Redirected to publish_pipeline.py"""
    return _pp_publish_payload_digest(title, desc, images, topics)


def publish_note(title, desc, images, topics, private=False):
    """Redirected to publish_pipeline.py — wires up all dependencies."""
    mcp_constants = {
        "connect_timeout": MCP_CONNECT_TIMEOUT,
        "start_wait": MCP_START_WAIT_SECONDS,
        "lock_max_wait": MCP_LOCK_MAX_WAIT,
        "lock_poll_interval": MCP_LOCK_POLL_INTERVAL,
        "stale_lock_minutes": MCP_STALE_LOCK_MINUTES,
        "http_timeout": MCP_HTTP_TIMEOUT,
        "max_attempts": MCP_MAX_ATTEMPTS,
        "retry_wait": MCP_RETRY_WAIT_SECONDS,
        "note_id_recovery_max_wait": MCP_NOTE_ID_RECOVERY_MAX_WAIT,
        "note_id_recovery_interval": MCP_NOTE_ID_RECOVERY_INTERVAL,
        "note_id_recovery_request_timeout": MCP_NOTE_ID_RECOVERY_REQUEST_TIMEOUT,
        "latest_feed_time_window": MCP_LATEST_FEED_TIME_WINDOW_SECONDS,
        "latest_feed_min_title_similarity": MCP_LATEST_FEED_MIN_TITLE_SIMILARITY_BPS,
    }
    return _pp_publish_note(
        title, desc, images, topics, private,
        mcp_constants=mcp_constants,
        mcp_fallback_on_fail=MCP_FALLBACK_ON_FAIL,
        check_cookie_expiry_fn=check_cookie_expiry,
        acquire_mcp_lock_fn=acquire_mcp_lock,
        release_mcp_lock_fn=release_mcp_lock,
        recover_note_id_from_mcp_fn=recover_note_id_from_mcp,
        extract_note_id_from_url_fn=_extract_note_id_from_url,
    )

# === End Phase 2.2 redirects ===


def main():
    import argparse
    parser = argparse.ArgumentParser(description="小红书笔记一键发布")
    parser.add_argument("markdown_file", nargs="?", help="Markdown 文件路径（恢复模式下可选）")
    parser.add_argument("output_dir", nargs="?", default=".", help="输出目录（默认：当前目录）")
    parser.add_argument("--num-images", type=int, default=1,
                       help="生成图片数量（1-9，默认1）")
    parser.add_argument("--private", action="store_true", help="发布为私密笔记（测试用）")
    parser.add_argument("--lock-type", default="narrative",
                       help="幂等锁类型（narrative/ai-digest/blog-digest/gegeewu-digest），隔离不同发布路径")
    parser.add_argument("--skip-check", action="store_true", help="跳过前置条件检查（快速测试）")
    parser.add_argument("--skip-cover", action="store_true",
                       help="跳过首图生成，仅生成分图（汇总/日报内容使用）")

    args = parser.parse_args()

    print("=== 小红书笔记一键发布 ===\n")

    # 幂等检查：今日是否已发布（仅 digest 类生效，narrative 不限制）
    _today_str = datetime.now().strftime("%Y-%m-%d")
    _lock_type = args.lock_type
    if _lock_type != "narrative":
        _already, _existing_id = check_published_today(_today_str, _lock_type)
        if _already:
            print(f"⚠️ 今日({_today_str})已发布[{_lock_type}]: {_existing_id}")
            print(f"   如需强制重发，删除: {get_published_lock_path(_today_str, _lock_type)}")
            sys.exit(0)

    # 恢复模式
    pending_data = read_pending_sync()
    if pending_data:
        mcp_recovery = {
            "max_wait": MCP_NOTE_ID_RECOVERY_MAX_WAIT,
            "interval": MCP_NOTE_ID_RECOVERY_INTERVAL,
            "request_timeout": MCP_NOTE_ID_RECOVERY_REQUEST_TIMEOUT,
        }
        exit_code = _orch_run_recovery_flow(
            pending_data,
            skill_dir=SKILL_DIR,
            python_bin=PYTHON_BIN,
            pending_sync_file=PENDING_SYNC_FILE,
            recover_note_id_from_mcp_fn=recover_note_id_from_mcp,
            clear_pending_sync_fn=clear_pending_sync,
            run_command_streaming_fn=run_command_streaming,
            mcp_recovery_constants=mcp_recovery,
        )
        sys.exit(exit_code)

    # 正常流程需要 markdown_file
    if not args.markdown_file:
        print("❌ 请提供 Markdown 文件路径")
        parser.print_help()
        sys.exit(1)

    md_file = Path(args.markdown_file)
    if not md_file.exists():
        print(f"❌ 文件不存在: {md_file}")
        sys.exit(1)

    if not 1 <= args.num_images <= 9:
        print("❌ 图片数量必须在 1-9 之间")
        sys.exit(1)

    if args.private:
        print("🔒 测试模式：将发布为私密笔记\n")

    mcp_recovery = {
        "max_wait": MCP_NOTE_ID_RECOVERY_MAX_WAIT,
        "interval": MCP_NOTE_ID_RECOVERY_INTERVAL,
        "request_timeout": MCP_NOTE_ID_RECOVERY_REQUEST_TIMEOUT,
    }
    exit_code = _orch_run_publish_flow(
        md_file=md_file,
        output_dir=args.output_dir,
        num_images=args.num_images,
        is_private=args.private,
        skip_check=args.skip_check,
        skip_cover=args.skip_cover,
        lock_type=_lock_type,
        today_str=_today_str,
        skill_dir=SKILL_DIR,
        python_bin=PYTHON_BIN,
        pending_sync_file=PENDING_SYNC_FILE,
        content_limit=PUBLISH_SOFT_CONTENT_LIMIT,
        mcp_content_max=MCP_CONTENT_MAX_LENGTH,
        soft_content_limit=PUBLISH_SOFT_CONTENT_LIMIT,
        mcp_recovery_constants=mcp_recovery,
        check_prerequisites_fn=check_prerequisites,
        parse_markdown_frontmatter_fn=parse_markdown_frontmatter,
        validate_digest_publish_input_fn=validate_digest_publish_input,
        prepare_content_fn=prepare_content,
        extract_tags_fn=extract_tags,
        enforce_content_limit_fn=enforce_content_limit,
        extract_generated_images_fn=extract_generated_images,
        run_command_streaming_fn=run_command_streaming,
        publish_note_fn=publish_note,
        recover_note_id_from_mcp_fn=recover_note_id_from_mcp,
        write_pending_sync_fn=write_pending_sync,
        mark_published_fn=mark_published,
        infer_task_id_from_images_fn=infer_task_id_from_images,
    )
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
